name = "dx3rd-idea"
compatibility_date = "2025-04-25"
compatibility_flags = ["nodejs_compat"]

[vars]
DISCORD_CLIENT_ID = "1358085922570240191"
REQUIRED_GUILD_ID = "1358094185848246363"
DISCORD_REDIRECT_URI = "http://localhost:3000/api/auth/discord/callback"

[[d1_databases]]
binding = "DB"
database_name = "idea-db"
database_id = "64a38857-c1bd-48ba-a940-33bee5260bc3"