name = "dx3rd-idea"
compatibility_date = "2025-04-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "idea-db"
database_id   = "5bf191d0-1a1e-4ed1-a8a1-d3c6c3e4accd"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Z3JhdGVmdWwtbmV3dC00LmNsZXJrLmFjY291bnRzLmRldiQ"
DISCORD_CLIENT_ID = "1358085922570240191"
DISCORD_TARGET_GUILD_ID = "1358094185848246363"