export const ITEM_CATEGORIES: {id:string, name:string}[] = [
    {id:"general-weapon", name:"ジェネラルアイテム:武器"},
    {id:"general-armor", name:"ジェネラルアイテム:防具"},
    {id:"general-vehicle", name:"ジェネラルアイテム:ヴィークル"},
    {id:"general-connection", name:"ジェネラルアイテム:コネ"},
    {id:"general-general", name:"ジェネラルアイテム:一般アイテム"},
    {id:"customize", name:"カスタマイズアイテム"},
    {id:"unique-weapon", name:"ユニークアイテム:武器"},
    {id:"unique-armor", name:"ユニークアイテム:防具"},
    {id:"unique-vehicle", name:"ユニークアイテム:ヴィークル"},
    {id:"unique-connection", name:"ユニークアイテム:コネ"},
    {id:"unique-item", name:"ユニークアイテム:一般アイテム"},
    {id:"unique-angelhalo", name:"ユニークアイテム:エンジェルハィロゥ"},
    {id:"unique-balor", name:"ユニークアイテム:バロール"},
    {id:"unique-blackdog", name:"ユニークアイテム:ブラックドッグ"},
    {id:"unique-bramstoker", name:"ユニークアイテム:ブラム=ストーカー"},
    {id:"unique-chimera", name:"ユニークアイテム:キュマイラ"},
    {id:"unique-exile", name:"ユニークアイテム:エグザイル"},
    {id:"unique-hanuman", name:"ユニークアイテム:ハヌマーン"},
    {id:"unique-morpheus", name:"ユニークアイテム:モルフェウス"},
    {id:"unique-neumann", name:"ユニークアイテム:ノイマン"},
    {id:"unique-orcus", name:"ユニークアイテム:オルクス"},
    {id:"unique-salamandra", name:"ユニークアイテム:サラマンダー"},
    {id:"unique-solaris", name:"ユニークアイテム:ソラリス"},
    {id:"unique-ouroboros", name:"ユニークアイテム:ウロボロス"},
    {id:"unique-gleipnir", name:"ユニークアイテム:グレイプニル"},
    {id:"create-angelhalo", name:"クリエイトアイテム:エンジェルハィロゥ"},
    {id:"create-balor", name:"クリエイトアイテム:バロール"},
    {id:"create-blackdog", name:"クリエイトアイテム:ブラックドッグ"},
    {id:"create-bramstoker", name:"クリエイトアイテム:ブラム=ストーカー"},
    {id:"create-chimera", name:"クリエイトアイテム:キュマイラ"},
    {id:"create-exile", name:"クリエイトアイテム:エグザイル"},
    {id:"create-hanuman", name:"クリエイトアイテム:ハヌマーン"},
    {id:"create-morpheus", name:"クリエイトアイテム:モルフェウス"},
    {id:"create-neumann", name:"クリエイトアイテム:ノイマン"},
    {id:"create-orcus", name:"クリエイトアイテム:オルクス"},
    {id:"create-salamandra", name:"クリエイトアイテム:サラマンダー"},
    {id:"create-solaris", name:"クリエイトアイテム:ソラリス"},
    {id:"create-ouroboros", name:"クリエイトアイテム:ウロボロス"},
    {id:"create-gleipnir", name:"クリエイトアイテム:グレイプニル"},
    {id:"effect-blackdog", name:"エフェクトアイテム:ブラックドッグ専用アイテム"},
    {id:"effect-servant", name:"エフェクトアイテム:従者専用アイテム"},
    {id:"effect-vehicle-morphing", name:"エフェクトアイテム:ヴィークルモーフィング専用アイテム"},
    {id:"effect-godslayer-blade", name:"エフェクトアイテム:神殺す刃専用アイテム"},
    {id:"effect-idea-holder", name:"エフェクトアイテム:イデアホルダー専用アイテム"},
    {id:"toybox", name:"秘密兵器専用アイテム"},
    {id:"legacy", name:"遺産継承者専用アイテム"},
    {id:"fh", name:"FHアイテム"},
    {id:"emblem-ugn-agent", name:"エンブレムアイテム:UGNエージェント"},
    {id:"emblem-ugn-branch-chief", name:"エンブレムアイテム:UGN支部長"},
    {id:"emblem-ugn-children", name:"エンブレムアイテム:UGNチルドレン"},
    {id:"emblem-ugn-hq-agent", name:"エンブレムアイテム:UGN本部エージェント"},
    {id:"emblem-ugn-axis", name:"エンブレムアイテム:アクシズ"},
    {id:"emblem-ugn-illegal", name:"エンブレムアイテム:UGNイリーガル"},
    {id:"emblem-ugn-common", name:"エンブレムアイテム:UGN共通"},
    {id:"emblem-fh-agent", name:"エンブレムアイテム:FHエージェント"},
    {id:"emblem-fh-cell-leader", name:"エンブレムアイテム:FHセルリーダー"},
    {id:"emblem-fh-children", name:"エンブレムアイテム:FHチルドレン"},
    {id:"emblem-fh-master-agent", name:"エンブレムアイテム:マスターエージェント"},
    {id:"emblem-fh-liaison-agent", name:"エンブレムアイテム:リエゾンエージェント"},
    {id:"emblem-fh-illegal", name:"エンブレムアイテム:FHイリーガル"},
    {id:"emblem-fh-common", name:"エンブレムアイテム:FH共通"},
    {id:"emblem-space-unity-association", name:"エンブレムアイテム:宇宙友愛協会"},
    {id:"emblem-overed-athlete", name:"エンブレムアイテム:オーヴァードアスリート"},
    {id:"emblem-kamishiro-group", name:"エンブレムアイテム:神城グループ"},
    {id:"emblem-guild", name:"エンブレムアイテム:ギルド"},
    {id:"emblem-special-investigations-agency", name:"エンブレムアイテム:公安警察特殊犯罪調査室"},
    {id:"emblem-kouou-society", name:"エンブレムアイテム:鴻央会"},
    {id:"emblem-state-of-grace", name:"エンブレムアイテム:ステイト・オブ・グレイス"},
    {id:"emblem-strangers", name:"エンブレムアイテム:ストレンジャーズ"},
    {id:"emblem-xenos", name:"エンブレムアイテム:ゼノス"},
    {id:"emblem-tindalos", name:"エンブレムアイテム:ティンダロス"},
    {id:"emblem-tempest", name:"エンブレムアイテム:テンペスト"},
    {id:"emblem-freelance", name:"エンブレムアイテム:フリーランス"},
    {id:"trail-chronicle", name:"トレイルアイテム:クロニクル"},
    {id:"trail-kikuchi", name:"トレイルアイテム:菊池リプレイ"},
    {id:"trail-breakup", name:"トレイルアイテム:ブレイクアップ"},
    {id:"trail-origin", name:"トレイルアイテム:オリジン"},
    {id:"trail-alive", name:"トレイルアイテム:アライブ"},
    {id:"trail-exodus", name:"トレイルアイテム:エクソダス"},
    {id:"trail-desire", name:"トレイルアイテム:デザイア"},
    {id:"relation-kiritani", name:"リレーションアイテム:霧谷雄吾"},
    {id:"relation-gora", name:"リレーションアイテム:強羅瑠璃"},
    {id:"relation-therese", name:"リレーションアイテム:テレーズ・ブルム"},
    {id:"relation-tamano", name:"リレーションアイテム:玉野椿"},
    {id:"relation-yakoji", name:"リレーションアイテム:薬王寺結希"},
    {id:"relation-ashe", name:"リレーションアイテム:アッシュ・レドリック"},
    {id:"relation-alfred", name:"リレーションアイテム:アルフレッド・J・コードウェル"},
    {id:"relation-johan", name:"リレーションアイテム:ヨハン・C・コードウェル"},
    {id:"relation-kasuga", name:"リレーションアイテム:春日恭二"},
    {id:"relation-hakamori", name:"リレーションアイテム:墓守清正"},
    {id:"relation-kurosu", name:"リレーションアイテム:黒須左京"},
    {id:"relation-tsuzuki", name:"リレーションアイテム:都築京香"},
    {id:"relation-aomine", name:"リレーションアイテム:青峰ミユキ"},
    {id:"relation-saginomiya", name:"リレーションアイテム:鷺乃宮キョウ"},
    {id:"relation-fionn", name:"リレーションアイテム:フィン・ブースロイド"},
    {id:"relation-rosa", name:"リレーションアイテム:ローザ・バスカヴィル"},
    {id:"relation-fujisaki", name:"リレーションアイテム:藤崎弦一"},
    {id:"relation-himemiya", name:"リレーションアイテム:姫宮由里香"},
    {id:"relation-senjoji", name:"リレーションアイテム:千城寺薫"},
    {id:"relation-amafune", name:"リレーションアイテム:天船巴"},
    {id:"relation-orido", name:"リレーションアイテム:織戸静馬"},
    {id:"relation-cesario", name:"リレーションアイテム:シザーリオ"},
    {id:"relation-sakatsuki", name:"リレーションアイテム:坂月那岐"},
    {id:"relation-kamishiro", name:"リレーションアイテム:神城早月"},
    {id:"relation-tatsumi", name:"リレーションアイテム:辰巳狛江"},
    {id:"relation-yaegashi", name:"リレーションアイテム:八重樫若菜"},
    {id:"relation-nekokawa", name:"リレーションアイテム:猫川美亜"},
]

export const ITEM_SUPPLEMENTS: string[] = [
    "基本1",
    "基本2",
    "上級",
    "PE",
    "IC",
    "UG",
    "RU",
    "EA",
    "LM",
    "HR",
    "RW",
    "CE",
    "BC",
    "NC",
    "IA",
    "UA",
]

export const ITEM_TYPES: string[] = [
    "指定なし",
    "武器",
    "防具",
    "ヴィークル",
    "コネ",
    "一般アイテム",
]
