export const POWER_TYPES: string[] = [
    "一般",
    "イージー",
    "エネミー",
    "変異種",
    "古代種",
    "申し子",
    "光使い",
    "闇使い",
    "雷帝",
    "吸血鬼",
    "黄昏の支配者",
    "異形",
    "神速の担い手",
    "音使い",
    "砂使い",
    "天才",
    "黄金領域",
    "動物使い",
    "永遠の炎",
    "優しい奇跡",
]

export const POWER_CATEGORIES: {id:string, name:string}[] = [
    {id:"angelhalo", name:"エンジェルハィロゥ"},
    {id:"balor", name:"バロール"},
    {id:"blackdog", name:"ブラックドッグ"},
    {id:"bramstoker", name:"ブラム=ストーカー"},
    {id:"chimaera", name:"キュマイラ"},
    {id:"exile", name:"エグザイル"},
    {id:"hanuman", name:"ハヌマーン"},
    {id:"morpheus", name:"モルフェウス"},
    {id:"neumann", name:"ノイマン"},
    {id:"orcus", name:"オルクス"},
    {id:"salamandra", name:"サラマンダー"},
    {id:"solaris", name:"ソラリス"},
    {id:"ouroboros", name:"ウロボロス"},
    {id:"mistilteinn", name:"ミストルティン"},
    {id:"gleipnir", name:"グレイプニル"},
    {id:"common", name:"一般"},
    {id:"rb", name:"RB"},
]

export const POWER_SUPPLEMENTS: string[] = [
    "基本1",
    "基本2",
    "上級",
    "IC",
    "RU",
    "EA",
    "LM",
    "HR",
    "RW",
    "CE",
    "BC",
    "IA",
    "UA",
]

export const POWER_TIMINGS: string[] = [
    "マイナーアクション",
    "メジャーアクション",
    "リアクション",
    "オートアクション",
    "セットアッププロセス",
    "イニシアチブプロセス",
    "クリンナッププロセス",
    "常時",
    "効果参照",
]

export const POWER_SKILLS: string[] = [
    "—",
    "シンドローム",
    "【肉体】",
    "〈白兵〉",
    "〈回避〉",
    "〈運転〉",
    "【感覚】",
    "〈射撃〉",
    "〈知覚〉",
    "〈芸術〉",
    "【精神】",
    "〈RC〉",
    "〈意志〉",
    "〈知識〉",
    "【社会】",
    "〈交渉〉",
    "〈調達〉",
    "〈情報〉",    
    "効果参照",
]

export const POWER_DFCLTIES: string[] = [
    "—",
    "自動成功",
    "対決",
    "20",
    "効果参照",
]

export const POWER_TARGETS: string[] = [
    "—",
    "自身",
    "単体",
    "2体",
    "3体",
    "5体",
    "[LV+1]体",
    "範囲",
    "範囲(選択)",
    "シーン",
    "シーン(選択)",
    "効果参照",
]

export const POWER_RNGS: string[] = [
    "—",
    "至近",
    "10m",
    "20m",
    "武器",
    "視界",
    "効果参照",
]

export const POWER_ENCROACHES: string[] = [
    "—",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "1D10",
    "2D10",
    "4D10",
    "6D10",
]

export const POWER_RESTRICTS: string[] = [
    "—",
    "80%",
    "100%",
    "120%",
    "200%",
    "ピュアブリード",
    "リミット",
    "従者専用",
    "RB",
    "Dロイス",
    "解放",
    "吸血",
    "飢餓",
    "殺戮",
    "破壊",
    "加虐",
    "嫌悪",
    "闘争",
    "妄想",
    "自傷",
    "恐怖",
    "憎悪",
    "改変",
    "効果参照",
]